@customerId = 1

### Get all customers
GET http://localhost:8080/api/customers

### Get customer by ID
GET http://localhost:8080/api/customers/{{customerId}}

### Create customer
POST http://localhost:8080/api/customers
Content-Type: application/json

{
  "firstName": "Klaudia",
  "lastName": "Nowak",
  "email": "klaudia.nowak@example.com",
  "phoneNumber": "500600700",
  "address": {
    "street": "Długa",
    "buildingNumber": "10A",
    "apartmentNumber": "5",
    "city": "Gdańsk",
    "postalCode": "80-831",
    "country": "Poland"
  }
}

### Delete customer by ID
DELETE http://localhost:8080/api/customers/{{customerId}}

### Partially update customer
PATCH http://localhost:8080/api/customers/1
Content-Type: application/json

{
  "lastName": "Kowalski",
  "phoneNumber": "+48 123 456 789"
}

### Update email
PATCH http://localhost:8080/api/customers/2
Content-Type: application/json

{
  "email": "ak.kowalska@example.com"
}
### Deactivate customer
PATCH http://localhost:8080/api/customers/1/deactivate

### Activate customer
PATCH http://localhost:8080/api/customers/999/activate
